### ISSUE TITLE
Introduce stylelint to codebase

### ISSUE THREAD

**Issue by hudochenkov** [ukparliament/parliament.uk-pugin#488]
I noticed that you use ESLint to avoid errors in JavaScript, but don't use any linter for stylesheets.

Would you consider to use [stylelint](https://stylelint.io/) to lint your stylesheets?

stylelint is a modern CSS linter that helps you avoid errors and enforce consistent conventions in your stylesheets.

I think you would be interested to start with [stylelint-config-recommended](https://github.com/stylelint/stylelint-config-recommended) to avoid error in stylesheets. And [stylelint-scss](https://github.com/kristerkari/stylelint-scss) plugin, which has many rules specific to SCSS.

**Comment by UsmanAfzal** [comment]
We won't be adding this right now as we are in the process of decommissioning the application.
